package com.example.model;


/* 

Used for the Database Mapping

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

It tells to the JPA that this class should be mapped to a table in a database
(Decorador de la clase)
@Entity

(Dentro de la clase)
@Id -> This annotation specifies the primary key of the entity.
@GeneratedValue(strategy = GenerationType.IDENTITY) -> This annotation indicates that the primary key value will be automatically generated by the database
*/

// Imports para reducir el boiler plate de getter's y setter's
import lombok.Getter;
import lombok.Setter;
import java.time.LocalDate;


// Blue print or structure for the main object, in this case the tasks


@SuppressWarnings("unused")
@Getter
@Setter
public class Task {

	private Long id;
    private String title;
	private String description;
	private boolean completed;
	private LocalDate dueDate;

    // Getters and Setters
}
